global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'ui'
    static_configs:
      - targets: ['weather-app-ui-1:3001']