apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather-con
        image: ahmedessam404/weather-2025:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: weather
              key: apikey


        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP 
        livenessProbe:
          httpGet:
            path: /
            port: http 
        readinessProbe:
          httpGet:
            path: /
            port: http 
        
